// require('dotenv').config() 

const CONFIG = {};
CONFIG.JWT = {
    SECRET: 'TEST_SECRET'
}
CONFIG.MODE = 'DEV';
CONFIG.PROD_MODE = CONFIG.MODE === 'DEV' ? false: true;
CONFIG.IS_CERT_AUTH_ENABLED = false;
CONFIG.CURRENCY= PROCESS.ENV.CURRENCY_LABEL;
CONFIG.TEST_GATEWAY = {
    BASEURL: PROCESS.ENV.GATEWAY_URL,
    API_VERSION: PROCESS.ENV.API_VERSION,
    USERNAME: 'merchant.' + PROCESS.ENV.MERCHANT_ID,
    PASSWORD: PROCESS.ENV.PASSWORD ,
    MERCHANTID: PROCESS.ENV.MERCHANT_ID
};
CONFIG.PKI_GATEWAY = {
    BASEURL: PROCESS.ENV.GATEWAY_URL ,
    API_VERSION: PROCESS.ENV.API_VERSION,
    MERCHANTID: PROCESS.ENV.MERCHANT_ID
}
CONFIG.WEBHOOKS = {
    WEBHOOKS_NOTIFICATION_SECRET : PROCESS.ENV.WEBHOOK_URL,
    WEBHOOKS_NOTIFICATION_FOLDER : 'webhooks-notifications'
}
CONFIG.SSL_FILES = {
    CRT: process.env.SSL_CRT_PATH,
    KEY: process.env.SSL_KEY_PATH
}
module.exports = CONFIG;